<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c37bfe42-1646-4af6-b646-1f689b180bbd</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/div[1]/div[2]/li[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='My\ profile'] .ant-dropdown-menu-title-content</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-dropdown-menu-title-content')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-dropdown-menu-title-content</value>
        <webElementGuid>820c60b1-f115-4274-bc54-daa45b6c1ae1</webElementGuid>
    </webElementProperties>
</WebElementEntity>