<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a1c4cf26-fcd9-4c81-8bf3-123eddd361a0</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(3) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(3) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cx-icon-btn ant-dropdown-trigger')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cx-icon-btn ant-dropdown-trigger</value>
        <webElementGuid>b0491949-d85a-4418-bb97-011e24787fa8</webElementGuid>
    </webElementProperties>
</WebElementEntity>