<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>658553a1-e286-4450-8db4-b73ace732d67</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[8]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='\33 739c1e9-ced6-481e-b5ed-8133a4b547be'] .cx-icon-btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cx-icon-btn ant-dropdown-trigger')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cx-icon-btn ant-dropdown-trigger</value>
        <webElementGuid>77d79bde-a648-4929-b74a-4efacfa78d74</webElementGuid>
    </webElementProperties>
</WebElementEntity>