<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ff3c96b3-6bbd-48f5-904f-59bf467e0bda</elementGuidId>
    <imagePath></imagePath>
    <name>button_9dbc2743-2f1d-483b-8459-75e2921c26d5_testing snaps</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="text-button "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'9dbc2743-2f1d-483b-8459-75e2921c26d5testing snapshot creation2024-04-03T03:58:36+00:00')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="SS_0398c7cf-73ce-4343-97c7-"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>9dbc2743-2f1d-483b-8459-75e2921c26d5
        testing snapshot creation
        2024-04-03T03:58:36+00:00</value>
        <webElementGuid>6a4a6be0-7e9a-4817-a86e-e09445a416bc</webElementGuid>
    </webElementProperties>
</WebElementEntity>