<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c1156199-83fe-4c0e-bc50-2ea50f68b9ba</elementGuidId>
    <imagePath></imagePath>
    <name>testim_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/testim-shadow-container[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>testim-shadow-container</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>testim-shadow-container</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>