<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3abf87dd-4026-4837-940f-8b89968d56a4</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[8]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='aff044dc-7917-44d6-b1cb-3341344cbee4'] .cx-icon-btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cx-icon-btn ant-dropdown-trigger')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cx-icon-btn ant-dropdown-trigger</value>
        <webElementGuid>1d144c46-ed94-405c-952d-b9135ff224bf</webElementGuid>
    </webElementProperties>
</WebElementEntity>