<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>971056d0-19f5-4d28-af3f-8a400908ebf7</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[2]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='profile\ menu']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cx-icon-btn ant-dropdown-trigger')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cx-icon-btn ant-dropdown-trigger</value>
        <webElementGuid>5ae34e41-36b7-4eac-a057-aac589c180f7</webElementGuid>
    </webElementProperties>
</WebElementEntity>