<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>299d7087-5a00-4215-8da1-d49720a9bdf0</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='aff044dc-7917-44d6-b1cb-3341344cbee4'] .text-button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'text-button ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>text-button </value>
        <webElementGuid>020f7feb-0767-415b-b50a-ec8545200827</webElementGuid>
    </webElementProperties>
</WebElementEntity>