<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8574d30f-ad93-47b8-89fd-c362846e70cf</elementGuidId>
    <imagePath></imagePath>
    <name>td_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='\33 739c1e9-ced6-481e-b5ed-8133a4b547be'] .cx-w-id-col</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-table-cell cx-w-id-col')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-table-cell cx-w-id-col</value>
        <webElementGuid>d8da09a4-0a38-4df0-ac7c-2611ba2bec2d</webElementGuid>
    </webElementProperties>
</WebElementEntity>