<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>527e2cb4-d36b-4cf9-ba00-8a73e89f2032</elementGuidId>
    <imagePath></imagePath>
    <name>td_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='c7aa8e10-ae7e-4762-967d-4a3148afefc9'] .cx-w-id-col</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-table-cell cx-w-id-col')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-table-cell cx-w-id-col</value>
        <webElementGuid>bd2847fa-b2e2-4654-b172-4432bac2df2e</webElementGuid>
    </webElementProperties>
</WebElementEntity>