<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>243a1f80-1da1-493b-8e08-0376cec0ebef</elementGuidId>
    <imagePath></imagePath>
    <name>td_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[6]/td[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='\37 2994f94-29cb-4e73-94de-9774328fe953'] .cx-w-id-col</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-table-cell cx-w-id-col')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-table-cell cx-w-id-col</value>
        <webElementGuid>1faa001a-cafc-403e-b28e-b521bb0fd1d1</webElementGuid>
    </webElementProperties>
</WebElementEntity>