<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c8f3f766-837c-4c70-8e92-5d0cb930a787</elementGuidId>
    <imagePath></imagePath>
    <name>td_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(3) &gt; :nth-child(1) &gt; :nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-table-cell cx-discription-col')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-table-cell cx-discription-col</value>
        <webElementGuid>59c44b2c-baa8-4b87-892e-b8c766ac2bdb</webElementGuid>
    </webElementProperties>
</WebElementEntity>