<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>572b7c2c-7c40-4aca-bee4-9a5f5e5ef676</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[6]/div[1]/div[1]/div[1]/ul[1]/li[4]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-dropdown-menu-item ant-dropdown-menu-item-active"] &gt; [class="ant-dropdown-menu-title-content"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Delete Environment"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>