<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>24abb219-6ac4-46cb-9f29-e58ed23dac87</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.cx-header</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cx-header home-bg')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cx-header home-bg</value>
        <webElementGuid>8353ea40-e0d1-4f8b-97f6-92fcf19b9b0c</webElementGuid>
    </webElementProperties>
</WebElementEntity>