<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8661a391-3e1f-4282-8ae3-52a5edb6026a</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.menu-item[aria-label='Edge\ Compute']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'menu-item ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>menu-item </value>
        <webElementGuid>f2a9283b-974a-447d-b938-92f8417715bb</webElementGuid>
    </webElementProperties>
</WebElementEntity>