<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>940e16dc-bfed-4422-9994-97f3efa21284</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_8</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.menu-item[aria-label='Dashboard']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'menu-item ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>menu-item </value>
        <webElementGuid>7f5bb159-a5cd-4359-b717-9c71e6a44eb4</webElementGuid>
    </webElementProperties>
</WebElementEntity>