<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a8060546-6fc1-4f95-85b1-17536a314aee</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.menu-item[aria-label='Activity']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'menu-item ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>menu-item </value>
        <webElementGuid>85523fa0-34e9-4784-a13f-3d9cf19e6a2c</webElementGuid>
    </webElementProperties>
</WebElementEntity>