<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>726d80f2-49d1-4d94-be0e-f41c520ebaee</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_7</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/button[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.menu-item[aria-label='Administration']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'menu-item ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>menu-item </value>
        <webElementGuid>d845fe81-1786-45c1-910e-59ed981711df</webElementGuid>
    </webElementProperties>
</WebElementEntity>