<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>784cf626-7925-4842-aa24-c8e0a6936a1b</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.menu-item[aria-label='Edge\ Compute\ 2\.0']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'menu-item ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>menu-item </value>
        <webElementGuid>4594c632-e58a-4218-9713-cb93d1fd72dc</webElementGuid>
    </webElementProperties>
</WebElementEntity>