<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a7e1d7f9-fd66-4ca7-9fff-246c732c48de</elementGuidId>
    <imagePath></imagePath>
    <name>form_login_info</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[2]/div[1]/div[2]/form[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'login_info')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>login_info</value>
        <webElementGuid>aed5c82b-fb9a-4f7d-b3af-282ef3ae9191</webElementGuid>
    </webElementProperties>
</WebElementEntity>