<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fdaef0f6-d4c5-4cd6-bd97-a14bc9e93880</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='a3ae24e8-d48e-46fc-91dc-6f2e2666932e'] .ant-dropdown-trigger</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-dropdown-trigger cx-manage-env-edb api-table-action-btn')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-dropdown-trigger cx-manage-env-edb api-table-action-btn</value>
        <webElementGuid>78ca8a29-da6e-434b-89d0-e9b831c9caa4</webElementGuid>
    </webElementProperties>
</WebElementEntity>