<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f1ce22cc-9e35-4e4b-8ab2-7f140723784d</elementGuidId>
    <imagePath></imagePath>
    <name>div_react_select_2_option_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-select-2-option-1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'react-select-2-option-1') and equals(@class,'react-select__option css-10wo9uf-option')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>react-select__option css-10wo9uf-option</value>
        <webElementGuid>298db6b6-2cb1-4fe8-8325-d3992748fe31</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>react-select-2-option-1</value>
        <webElementGuid>e79fb98b-61b0-4b47-9dac-06a5eaf91de5</webElementGuid>
    </webElementProperties>
</WebElementEntity>