<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aa76910f-dc4b-4ce2-b7b9-3c0dea3abe86</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='\33 3b3108a-b39c-4c25-a013-651a534792c9'] .ant-dropdown-trigger</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-dropdown-trigger cx-manage-env-edb ssh-table-action-btn')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-dropdown-trigger cx-manage-env-edb ssh-table-action-btn</value>
        <webElementGuid>353bde52-46cc-4594-ac3a-fc8373c108b6</webElementGuid>
    </webElementProperties>
</WebElementEntity>