<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1c6ab345-f18a-49ee-b09b-3c5553c9d3a8</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='IPv6\ Rules']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'tab-item false')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>tab-item false</value>
        <webElementGuid>2bf1f639-cce3-4482-830b-4b941db7bf39</webElementGuid>
    </webElementProperties>
</WebElementEntity>