<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c472c5ec-b9e7-47b9-bcf7-168d6feb4cf8</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Linked\ Instances']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'tab-item false')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>tab-item false</value>
        <webElementGuid>c0979e82-4fac-40f6-9554-50cccfd9b7c3</webElementGuid>
    </webElementProperties>
</WebElementEntity>