<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ad72ae84-f66c-46f3-950e-e3695ff6229f</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='edit']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cx-icon-btn ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cx-icon-btn </value>
        <webElementGuid>6cd774e6-5d48-431b-9589-5d53b0eeee7b</webElementGuid>
    </webElementProperties>
</WebElementEntity>