<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ca5a7879-5e6e-4cd5-a4dd-5c98782f970f</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.anticon-close</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'anticon anticon-close')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>anticon anticon-close</value>
        <webElementGuid>c7090cea-0ffd-40f6-b76c-e89e793449f0</webElementGuid>
    </webElementProperties>
</WebElementEntity>