<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>df675aa0-58a7-4395-99a7-1c7ecb1bdd6b</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='\33 61d0da2-3bf9-4f95-a9f2-7fc45bb20ed0'] .env-name-col</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'env-name-col')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>env-name-col</value>
        <webElementGuid>37725c32-eccd-4e01-8351-7d249b67bf2d</webElementGuid>
    </webElementProperties>
</WebElementEntity>