<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>573aa446-4823-4f7c-911e-1683d549387a</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='\37 0e2ba81-0653-4b68-aab8-f4d4a2d1c671'] .env-name-col</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'env-name-col')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>env-name-col</value>
        <webElementGuid>45f0295c-99db-4d2e-8695-cc4e25a8bf1f</webElementGuid>
    </webElementProperties>
</WebElementEntity>