<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de711854-600b-4386-afa6-2031e6d7c049</elementGuidId>
    <imagePath></imagePath>
    <name>td_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(3) &gt; :nth-child(3) &gt; :nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-table-cell')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-table-cell</value>
        <webElementGuid>6ff111c1-6364-48e9-9288-82a0ca3364fa</webElementGuid>
    </webElementProperties>
</WebElementEntity>