<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>29dd8e04-9ee2-423d-ba58-5356225643cf</elementGuidId>
    <imagePath></imagePath>
    <name>p_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/p[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="cx-w-tab"] &gt; [class="cx-section-title"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>p &gt;&gt; internal:has-text="Edge Compute"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>