<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>53f909d4-00f3-4f12-933c-39c24158fd01</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[8]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-row-key='dfdd2ba7-355c-48ac-9eef-bc89827ee882'] .cx-icon-btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cx-icon-btn ant-dropdown-trigger')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cx-icon-btn ant-dropdown-trigger</value>
        <webElementGuid>309ec0ec-82b1-4bcb-b44f-571c27433d4a</webElementGuid>
    </webElementProperties>
</WebElementEntity>