<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1608efb6-aa46-4565-aa77-64edf33fbf56</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[8]/div[1]/div[1]/div[1]/ul[1]/li[2]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Delete'] .ant-dropdown-menu-title-content</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-dropdown-menu-title-content')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-dropdown-menu-title-content</value>
        <webElementGuid>24b80a58-3f13-4a73-8b30-12244e0e2b91</webElementGuid>
    </webElementProperties>
</WebElementEntity>