<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>62e8aff1-07bf-4ce3-8473-d4962707c02b</elementGuidId>
    <imagePath></imagePath>
    <name>button_testing standard user</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[2]/button[27]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="switch_org_label"]:nth-child(28)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Testing Standard User')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Testing Standard User"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Testing Standard User</value>
        <webElementGuid>6a4a6be0-7e9a-4817-a86e-e09445a416bc</webElementGuid>
    </webElementProperties>
</WebElementEntity>