<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>45b6260e-18e2-497a-919b-c262348d33fa</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/span[1]/span[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-input-affix-wrapper ant-input-affix-wrapper-focused"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ant-input-affix-wrapper</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>