<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>465187de-de00-46de-931d-445a73e53a46</elementGuidId>
    <imagePath></imagePath>
    <name>div_testssh</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='TestSSH']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ant-select-item ant-select-item-option ant-select-item-option-grouped') and equals(@title,'TestSSH')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-select-item ant-select-item-option ant-select-item-option-grouped</value>
        <webElementGuid>a5e4008f-d7bf-4589-bea1-339f00ce3aee</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>TestSSH</value>
        <webElementGuid>b7b6b77a-7cdd-43c3-8ff8-f89268f52227</webElementGuid>
    </webElementProperties>
</WebElementEntity>