<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>867e193c-4ad7-4e60-8d99-9beac5f7f326</elementGuidId>
    <imagePath></imagePath>
    <name>input_label</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Enter\ server\ label']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'label') and equals(@class,'common-input-style port-number')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>common-input-style port-number</value>
        <webElementGuid>a5ef1d7d-f55b-4147-9ae3-12d04c4c18d8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>label</value>
        <webElementGuid>d26e914f-dee8-4307-a40b-aa4c5951e010</webElementGuid>
    </webElementProperties>
</WebElementEntity>