<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f4c435e0-a5f8-40e0-a48c-893c4031bab6</elementGuidId>
    <imagePath></imagePath>
    <name>input_hostname</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Enter\ server\ hostname']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'hostname') and equals(@class,'common-input-style port-number')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>common-input-style port-number</value>
        <webElementGuid>9113397a-f1ec-431d-bbac-df8ec330c20b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>hostname</value>
        <webElementGuid>b225b098-a004-4c3c-b398-89c84181b564</webElementGuid>
    </webElementProperties>
</WebElementEntity>